### ISSUE TITLE
API goes down after some tests

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#145] opened 2016-09-20 21:52 UTC
It seems that the API stops working after some tests.... this must be fixed before launch

**Comment by swapzone** [comment] 2016-09-21 03:58
@davidtran Nam can you please have a look into the logs and see what goes wrong? I will fix it once we know what the problem is.

**Comment by davidtran** [comment] 2016-09-21 04:08
There is an issue, if search engine returns empty result for any appointment. The website will discard the whole appointments result and show a no result message box...

I will fix this issue, it will show results for any success searches. When user clicks to empty result appointment, it will show "No search result for this appointment". 

How do you think ?

**Comment by swapzone** [comment] 2016-09-21 04:09
Makes sense to me. Do you see, why it returns an empty response?

**Comment by davidtran** [comment] 2016-09-21 04:13
As I've observed, when the distance between 2 locations is too far and there is no flight on chose date. It will return an "[]" in search result... It usually occurs in return to origin trip.

May be in this case, we should allow user to choose another return date or edit the appointment.

**Comment by swapzone** [comment] 2016-09-21 04:44
Okay, Ruediger should first figure out, in which cases this happens, then we can think about how to solve it.

**Comment by GrosR** [comment] 2016-09-21 06:23
at the moment it seems, that it happens every few tests..afterwards it is not possible to recover the system to do further tests, so I can´t test anything. When it happened the first time, Nam told me he fixed the API integration, but I don´t know what he did exactly

**Comment by davidtran** [comment] 2016-09-21 07:35
When it happened the first time, it's the permission issue cause by PM2 ( a software to keep node instance running ) so I have to run the API server manually, when I turned off my computer, the API server stops too. So I've fixed the permission issue with PM2 and it worked.

**Comment by davidtran** [comment] 2016-12-05 11:09
We can close this issue since we have fixed it.

**Closed by davidtran** 2016-12-05 11:09 UTC
Labels: bug
