### ISSUE TITLE
font styling bugs

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#138] opened 2016-09-04 12:36 UTC
I think that the font selection in the app is neither conistent nor does it match the fonts used in the mockups created by Damian. 

In Damians mockups, the fonts look harmonic and smooth, in the app it seems to be a mixture of fonts, sizes and styles that is not consistent.

**Comment by damianmartone** [comment] 2016-09-05 08:13
have you checked the html templates too? to see if its in the app that the problem is or in the source? using the sass files, font styles should be fixed and the same

**Comment by davidtran** [comment] 2016-09-05 09:14
I am comparing the sass file from the app and the html template.

**Comment by GrosR** [comment] 2016-09-06 11:40
I  still think that the font for the chosen trip is not correct: 
![image](https://cloud.githubusercontent.com/assets/11087531/18272316/760f1482-7437-11e6-976d-83cb2f14d12d.png)

The font looks like sth. different as the rest

**Comment by davidtran** [comment] 2016-09-19 08:50
Font is updated.

**Closed** 2016-09-20 21:53 UTC
Labels: bug
